name: Node.js CI

on:
  push:
    branches: [main, dev/*]
  pull_request:
    branches: [main, dev/*]
         
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
         working-directory: ./
        
    strategy:
      matrix:
        node-version: [23.11]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - run: pwd
    - run: ls -a
    - run: cd ..
    - run: pwd
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run test:prod
    - run: npm run lint 
