name: Node.js CI

on:
  push:
    branches: [main, dev/*]
  pull_request:
    branches: [main, dev/*]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front

    strategy:
      matrix:
        node-version: [23.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - run: pwd
    - run: ls -a
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: front/package-lock.json
    - run: npm ci
    - run: npm run test:prod
    - run: npm run lint
